config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :sales
  end
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  has_many :variant_sales, through: :variants_including_master

  def on_sale?(user = nil)
    return true if user && variant_sales.active.exists?(user: user)
    variant_sales.active.exists?(user: nil)
  end
end

app/models/spree/products_taxon.rb
module Spree
  class ProductsTaxon < ActiveRecord::Base
  end
end

app/models/spree/sale.rb
module Spree
  class Sale < ActiveRecord::Base
    has_many :variant_sales, dependent: :destroy

    has_many :sale_taxons, dependent: :destroy
    has_many :taxons, through: :sale_taxons
    has_many :sale_products, dependent: :destroy
    has_many :products, through: :sale_products
    has_many :sale_user_groups, dependent: :destroy
    has_many :user_groups, through: :sale_user_groups
    has_many :sale_users, dependent: :destroy
    has_many :users, through: :sale_users
    has_many :sale_variants, dependent: :destroy
    has_many :variants, through: :sale_variants

    enum sale_type: [:percent, :fixed]

    validates_presence_of :name, :start_date, :amount, :sale_type
    validate :end_date_greater_than_start_date?

    def active?
      return false if Time.zone.now < start_date
      return false if end_date && Time.zone.now > end_date
      true
    end

    def end_date_greater_than_start_date?
      return if end_date.blank? || end_date > start_date

      errors.add(:end_date, 'must be greater than start date')
    end
  end
end

app/models/spree/sale_product.rb
class Spree::SaleProduct < ActiveRecord::Base
  belongs_to :sale
  belongs_to :product
end

app/models/spree/sale_taxon.rb
class Spree::SaleTaxon < ActiveRecord::Base
  belongs_to :sale
  belongs_to :taxon
end

app/models/spree/sale_user.rb
class Spree::SaleUser < ActiveRecord::Base
  belongs_to :sale
  belongs_to :user
end

app/models/spree/sale_user_group.rb
class Spree::SaleUserGroup < ActiveRecord::Base
  belongs_to :sale
  belongs_to :user_group
end

app/models/spree/sale_variant.rb
class Spree::SaleVariant < ActiveRecord::Base
  belongs_to :sale
  belongs_to :variant
end

app/models/spree/user_decorator.rb
Spree::User.class_eval do
  def self.current
    Thread.current[:user]
  end

  def self.current=(user)
    Thread.current[:user] = user
  end
end

app/models/spree/variant_decorator.rb
Spree::Variant.class_eval do
  has_many :variant_sales
  has_many :sales, through: :variant_sales

  def price_in(currency)
    return sale_price_in(currency) if sale_price
    prices.select{ |price| price.currency == currency }.first || Spree::Price.new(variant_id: self.id, currency: currency)
  end

  def sale_price_in(currency)
    Spree::Price.new(variant_id: self.id, amount: sale_price, currency: currency)
  end

  def sale_price
    @sale_price ||= begin
      return if active_sale.nil?

      if active_sale.sale.percent?
        price - (price * active_sale.sale.amount / 100.0)
      else
        price - active_sale.sale.amount
      end
    end
  end

  def on_sale?(user = nil)
    active_sale(user).present?
  end

  def active_sale(user = Spree::User.current)
    @active_sale ||= if user && variant_sales.active.exists?(user: user)
                       variant_sales.active.where(user: user).first
                     else
                       variant_sales.active.where(user: nil).first
                     end
  end
end

app/models/spree/variant_sale.rb
module Spree
  class VariantSale < ActiveRecord::Base
    belongs_to :variant
    belongs_to :sale
    belongs_to :user

    validates_presence_of :variant_id, :sale_id

    scope :active, -> { where('? >= start_date AND (end_date IS NULL OR ? < end_date)', Time.zone.now, Time.zone.now) }
  end
end

app/models/user_decorator.rb
User.class_eval do
  def self.current
    Thread.current[:user]
  end

  def self.current=(user)
    Thread.current[:user] = user
  end
end

app/controllers/application_controller_decorator.rb
ApplicationController.class_eval do
  before_filter :set_current_user

  def set_current_user
    Spree::User.current = spree_current_user
  end
end

app/controllers/spree/admin/sales_controller.rb
module Spree
  module Admin
    class SalesController < Spree::Admin::ResourceController
      before_action :prepare_array_params, only: [:create, :update]

      def index
        @sales = Spree::Sale.all.order('start_date desc')
      end

      def new
        @sale = Spree::Sale.new
      end

      def create
        @sale = SaleCreator.create(sale_params)
        respond_with @sale, location: polymorphic_url([:admin, :sales])
      end

      def edit
        set_sale
      end

      def update
        set_sale
        @sale = SaleCreator.create(sale_params, @sale)
        respond_with @sale, location: polymorphic_url([:admin, :sales])
      end

      private

      def set_sale
        @sale = Spree::Sale.find(params[:id])
      end

      def sale_params
        params.require(:sale).permit(:name, :description, :amount, :sale_type,
                                     :start_date, :end_date,
                                     taxon_ids: [], product_ids: [], variant_ids: [],
                                     user_group_ids: [], user_ids: [])
      end

      def prepare_array_params
        [:taxon_ids, :product_ids, :user_group_ids, :user_ids, :variant_ids].each do |key|
          if params[:sale][key].present?
            params[:sale][key] = params[:sale][key].split(',')
          else
            params[:sale][key] = []
          end
        end
      end
    end
  end
end

app/views/spree/admin/sales/_form.html.slim
= render :partial => "spree/admin/variants/autocomplete", :formats => :js

= simple_form_for [:admin, sale] do |f|
  .row
    .col-md-12
      = f.input :name, input_html: { class: 'with-tip', title: t('admin.tooltips.sales_name') }
  .row
    .col-md-12
      = f.input :description, input_html: { class: 'with-tip', title: t('admin.tooltips.sales_description') }
  .row
    .col-md-6
      = f.input :start_date, as: :string, input_html: { class: 'datepicker with-tip', title: t('admin.tooltips.sales_start_date'), value: datepicker_field_value(@sale.start_date) }
    .col-md-6
      = f.input :end_date, as: :string, input_html: { class: 'datepicker with-tip', title: t('admin.tooltips.sales_end_date'), value: datepicker_field_value(@sale.end_date) }
  .row
    .col-md-6
      = f.input :sale_type, input_html: { class: 'with-tip', title: t('admin.tooltips.sales_sale_type') }, collection: Spree::Sale.sale_types.keys.map {|sale| [sale.titleize, sale]}
    .col-md-6
      = f.input :amount, input_html: { class: 'with-tip', title: t('admin.tooltips.sales_amount') }
  
  .row
    .col-md-6 class='with-tip' data-original-title= t('admin.tooltips.sales_user_groups')
      = f.label :user_group_ids, 'User groups'
      = f.hidden_field :user_group_ids, value: @sale.user_group_ids.join(','), class: 'user_group_picker'

    .col-md-6 class='with-tip' data-original-title= t('admin.tooltips.sales_users')
      = f.label :user_ids, 'Users'
      = f.hidden_field :user_ids, value: @sale.user_ids.join(','), class: 'user_picker'
          
  .row
    .col-md-6 class='with-tip' data-original-title= t('admin.tooltips.sales_taxon')
      = f.label :taxon_ids, 'Taxons'
      = f.hidden_field :taxon_ids, value: @sale.taxon_ids.join(',')
        - if @sale.taxons.any?
          ul.text_list
            - sale.taxons.each do |taxon|
             li = taxon.name
        - else
          .alert.alert-info = Spree.t(:no_resource_found, resource: :taxons)

    .col-md-6 class='with-tip' data-original-title= t('admin.tooltips.sales_products')
      = f.label :product_ids, 'Products'
      = f.hidden_field :product_ids, value: @sale.product_ids.join(','), class: 'product_picker'
  
  .row
    .col-md-12 class='with-tip' data-original-title= t('admin.tooltips.sales_variants')
      = f.label :variant_ids, 'Variants'
      = f.hidden_field :variant_ids, value: @sale.variant_ids.join(','), class: 'variant_autocomplete_multiple fullwidth-input'

  - if sale.persisted?
    = render 'spree/admin/shared/edit_resource_links'
  - else
    = render 'spree/admin/shared/new_resource_links'

app/views/spree/admin/sales/edit.html.slim
= render 'spree/admin/shared/error_messages', target: @sale

- content_for :page_title, 'Edit Sale'

= render 'form', sale: @sale

app/views/spree/admin/sales/index.html.slim
- content_for :page_title, 'Sales'

- content_for :page_actions do
  = button_link_to t("admin.new_sale"), new_admin_sale_path, class: "btn-success", icon: 'add', id: 'admin_new_sale'

- if @sales.any?
  table.table.sortable id="listing_companies"
    thead
      tr
        th Name
        th Starts at
        th Ends at
        th.actions
    tbody
      - @sales.each do |sale|
        tr id="#{ spree_dom_id sale }" class="#{ cycle('odd', 'even') }"
            td = link_to sale.name, edit_admin_sale_path(sale)
            td = sale.start_date
            td = sale.end_date
            td.actions.actions-2.text-right
              = link_to_edit sale, no_text: true, class: 'edit' if can?(:edit, sale)
              = link_to_delete sale, no_text: true if can?(:delete, sale)
- else
  .alert.alert-info.no-objects-found
    = Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Sale))
    = link_to Spree.t(:add_one), new_admin_sale_path

app/views/spree/admin/sales/new.html.slim
= render 'spree/admin/shared/error_messages', target: @sale

- content_for :page_title, 'New Sale'

= render 'form', sale: @sale